### ISSUE TITLE
ERROR: LoadError: UndefVarError: distribute not defined

### ISSUE THREAD

**Issue by M-Marz** [JuliaOptimizers/Krylov.jl#1]
Hi,

When I try to use the cg_lanczos_shift_par function I get the error:

   ERROR: LoadError: UndefVarError: distribute not defined

Thank you very much for your help!

**Comment by dpo** [comment]
What version of Julia are you using?

**Comment by M-Marz** [comment]
It is Version 0.4.0-dev+4196 (2015-04-10 03:14 UTC)







Sent from Windows Mail





From: Dominique
Sent: ‎Monday‎, ‎April‎ ‎13‎, ‎2015 ‎6‎:‎12‎ ‎PM
To: optimizers/Krylov.jl
Cc: M-Marz





What version of Julia are you using?

**Comment by dpo** [comment]
The error probably occurs because distributed vectors were factored out of Julia base in version 0.4. I should be able to fix that tomorrow.

**Comment by dpo** [comment]
It turned out that compatibility with 0.4 was nontrivial and required changes to LinearOperators.jl as well. You'll want to update that and give the `julia-v04` branch a try. Let me know how it goes.

**Comment by dpo** [comment]
Closing this. Feel free to open a new issue if problems remain.
